version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 679029767004.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t lambda-docker-repo .
      - docker tag lambda-docker-repo:latest 679029767004.dkr.ecr.us-east-1.amazonaws.com/lambda-docker-repo:latest

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 679029767004.dkr.ecr.us-east-1.amazonaws.com/lambda-docker-repo:latest
      - echo Creating imagedefinitions.json file...
      - printf '[{"name":"lambda","imageUri":"%s"}]' 679029767004.dkr.ecr.us-east-1.amazonaws.com/lambda-docker-repo:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json