version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 679029767004.dkr.ecr.us-east-1.amazonaws.com
      - IMAGE_REPO=679029767004.dkr.ecr.us-east-1.amazonaws.com/pipeline-test
      - TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $IMAGE_REPO:$TAG .
      - docker push $IMAGE_REPO:$TAG
  post_build:
    commands:
      - echo "Writing image definitions..."
      - printf '[{"name":"app-container","imageUri":"%s"}]' $IMAGE_REPO:$TAG > imagedefinitions.json
      - echo $TAG > imageDetail.txt

artifacts:
  files:
    - imagedefinitions.json
    - imageDetail.txt
    - appspec.yml
    - scripts/*